%YAML:1.0
# data

# camera config
frame_width: 640
frame_height: 480
frame_fps: 30
emitter_enabled: 1    # 0 或 1，代表是否使能红外激光发射器
laser_power_ratio: 1   # 0~1，range.min + (range.max - range.min)*laser_power_ratio
auto_exposure_mode: 1  # 0 或 1，是否使用自动调节曝光时间，如果是1，那么exposure_ratio就不起作用，因为是自动调节的
exposure_ratio: 0.5    # 0~1，range.min + (range.max - range.min)*exposure_ratio

# VO paras
number_of_features: 500
scale_factor: 1.035
level_pyramid: 8
match_ratio: 2.0
max_num_lost: 10
min_inliers: 10
keyframe_rotation: 0.1
keyframe_translation: 0.1
map_point_erase_ratio: 0.1